### PR TITLE
MINOR: fixing link to Manuscript Academy Podcast

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @BolajiAyodeji 

just a small fix: the link for the Manuscript Academy Podcast was broken.

Cheers!

### CODE REVIEW

**Review by BolajiAyodeji — APPROVED** [review]
Thanks for this amazing PR!

**Comment by BolajiAyodeji** [comment]
@all-contributors, please add @spekulatius for docs.

**Comment by BolajiAyodeji** [comment]
@all-contributors please add @spekulatius for docs

**Comment by spekulatius** [comment]
No problem at all! Happy to help out!

**Pull request merged**
